
CREATE DATABASE TIEN_SIEUTHISACH

GO

USE TIEN_SIEUTHISACH

GO

CREATE TABLE NHAXUATBAN
(
    MaNXB NVARCHAR(100)  PRIMARY KEY,
	TenNXB NVARCHAR(100) NOT NULL,
	Diachi NVARCHAR(100) NOT NULL,
	)

GO
CREATE TABLE TACGIA
(
   Matacgia NVARCHAR (100) PRIMARY KEY ,
   Tentacgia NVARCHAR(100) NOT NULL,
   Dienthoai VARCHAR(100) NOT NULL,

   )
  GO

CREATE TABLE SACH
(
    MASACH VARCHAR(100) PRIMARY KEY,
	TENSACH VARCHAR (100) NOT NULL,
	GIA MONEY NOT NULL,
	MANXB NVARCHAR (100) NOT NULL,
	NAMXB DATETIME  NOT NULL,

	FOREIGN KEY (MANXB) REFERENCES NHAXUATBAN (MANXB),
	)

GO
CREATE TABLE SACH_TACGIA
( 
     MATACGIA NVARCHAR(100) NOT NULL,
	 MASACH VARCHAR(100) NOT NULL,
	 PRIMARY KEY(MATACGIA, MASACH),


	 FOREIGN KEY (matacgia) REFERENCES TACGIA (matacgia),
	 FOREIGN KEY (MASACH) REFERENCES SACH (MASACH),
)